### ISSUE TITLE
直接忽略 system 对话是否合适？

### ISSUE THREAD

**Issue by xiaotianxt** [sxz799/gemini2chatgpt#1]
https://github.com/sxz799/gemini2chatgpt/blob/a30cdbdfdf6a431106d33ac9ae58f2e0e79e5841/service/doTrans.go#L30C1-L31C1

既然这个项目是用来将 Gemini 模拟成 ChatGPT 结构，直接把 system 类型的对话扔掉会不会不太合适？

我的想法：考虑将 system 对话直接写作 ====INSTRUCTION START==== {SYSTEM} ====INSTRUCTION END====，插入在 user 的最前端？

**Comment by sxz799** [comment]
Chat next web默认开启的一个system包含chatgpt 会导致gemini不回复消息

**Comment by sxz799** [comment]
> https://github.com/sxz799/gemini2chatgpt/blob/a30cdbdfdf6a431106d33ac9ae58f2e0e79e5841/service/doTrans.go#L30C1-L31C1
> 
> 既然这个项目是用来将 Gemini 模拟成 ChatGPT 结构，直接把 system 类型的对话扔掉会不会不太合适？
> 
> 我的想法：考虑将 system 对话直接写作 ====INSTRUCTION START==== {SYSTEM} ====INSTRUCTION END====，插入在 user 的最前端？
